name: tech_store
description: Simple online tech store (mock data).
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
